### ISSUE TITLE
Represent circles in flight plan dataset

### ISSUE THREAD

**Issue by d70-t** [orcestra-campaign/pyorcestra#25]
The flight plan dataset, which results from `expand_path` should finally carry all relevant information about the flight. For now it lacks a good explicit representation of circles, which makes it harder to create good concise summaries based on that dataset alone.

We should find a representation for circles.
I could imagine adding a `circle` coordinate which would enumerate all circles. And then variables which describe the circle (e.g. center, radius, entry point, exit point, angle etc..), as well as the relation to the path points (e.g. index of first point in circle and index of last point in circle).

**Comment by lkluft** [comment]
Solved in #60
