### ISSUE TITLE
kwargs in path_preview

### ISSUE THREAD

**Issue by bjorn-stevens** [orcestra-campaign/pyorcestra#38]
When using path_preview it worked well to simply write
```python
path   = LatLon(lat=tracks['IRS_LAT'], lon=tracks['IRS_LON'], label='HALO-20240811a')
```
where `tracks` was a BAHAMAS file.   However, when doing this I got the complaint that I did specify waypoints.  `path_preview` calls `plot_path` which allows one to specify `show_waypoints=False` which then eliminates the error, however without `kwargs` I couldn't pass this down from the higher level call.  Would it  e better to use `kwargs`, also for keywords like color etc. 

I could make a pull request with my code with these changes, but thought to raise the issue first as there is likely a better solution.

**Comment by lkluft** [comment]
Closed in #43
