### ISSUE TITLE
pyorcestra Fails to install due to error with healpy on Windows

### ISSUE THREAD

**Issue by danielrowe9193** [orcestra-campaign/pyorcestra#57]
Hi this is Daniel, I am trying to import the orcestra module, and within the installation process I get this error when healpy is being compiled:
```bash
error: [WinError 193] %1 is not a valid Win32 application
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for healpy
Failed to build healpy
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (healpy)
```
I am using windows 11 (and my coworker who received the same error uses Windows 10), I have tried using other virtual environments like mamba, and I tried installing healpy externally, and I received the same error.

My coworker interestingly gets some of his blocks of code to work even though healpy did not compile for him too.

**Comment by lkluft** [comment]
The healpy package doesn't support Windows (see https://github.com/healpy/healpy/issues/25). Although the developers do not oppose adding support for Windows, the issues is open for 12 [sic!] years now, so I don't expect a solution in the near future.

A mid-term solution would be for `easygems` and `pyorcestra` to switch to another HEALPix backend (see https://github.com/mpimet/easygems/issues/11). However, this will definitely not happen during the campaign.

Fortunately, pyorcestra only requires healpy for a single quick look function. Therefore, I opened #58 which would remove the hard dependency on healpy. If this gets merged, future releases of pyorcestra should be installable on Windows

**Comment by danielrowe9193** [comment]
Thank you a lot for the assistance. When will the next version be released?

**Comment by lkluft** [comment]
Well, at the moment we are still discussing whether this actually solves the dependency problem for Windows users (see the public thread at #58).

**Comment by danielrowe9193** [comment]
Okay thank you.
