### ISSUE TITLE
 pre-commit ruff vs ruff

### ISSUE THREAD

**Issue by hgloeckner** [orcestra-campaign/pyorcestra#84]
Hello, 

I realized just now that the pre-commit configuration for ruff does not match the `ruff format` command formatting, meaning that if I have pre-commit installed and accept those ruff formating changes, it does not necessarily pass the pipeline. 

Now, I could just uninstall pre-commit, but maybe we could also have those in sync somehow?

**Comment by d70-t** [comment]
Uh, that's bad. It has to be the same...
Can you fix it?
